### ISSUE TITLE
SHGO?

### ISSUE THREAD

**Issue by microprediction** [daxiongshu/rapids-ai-BBO-2nd-place-solution#6]
I'm not seeing shgo on the list. Did I miss it?

**Comment by daxiongshu** [comment]
Is `SHGO` an optimizer? We only used the given optimizers in the [competition starting kit](https://github.com/rdturnermtl/bbo_challenge_starter_kit/tree/master/example_submissions), namely, `turbo`, `skopt`, `hyperopt`, `nevergrad`, `opentuner` and `pysot`. `nevergrad` was discarded since it crashes randomly with GPU-based models.

**Comment by daxiongshu** [comment]
We also reduced the install list to just what we need so a lot packages in the [original requirement](https://github.com/rdturnermtl/bbo_challenge_starter_kit/blob/master/environment.txt) are not installed for this solution.

**Comment by microprediction** [comment]
Yeah it is one of the options in scipy.optimize. Found it worked quite well for some problems dim<10. 
https://www.microprediction.com/blog/optimize
Nice work btw. Very interesting to see the mixing.

**Comment by daxiongshu** [comment]
Thank you! And thank you for the link. We'll definitely check it out. I'll close this issue for now. Please raise a new issue or leave a comment here if you have more questions.
